@startuml
titleLabel Add column
Actor User

User->ButtonWidget: Presses button
ButtonWidget -> TableDesignHandler: addColumn()
activate TableDesignHandler
TableDesignHandler -> Table: addColumn()
activate Table
create Column
Table -> Column: create Column(N)
activate Column
Column -> Column: setName("ColumnN")
return Column
loop for all Rows
    Table -> Column: addCell()
    activate Column
    create Cell
    Column -> Cell: create()
    deactivate Column
end
deactivate Table
deactivate TableDesignHandler
ButtonWidget -> UIWindowHandler: getOpenTable()
activate UIWindowHandler
ButtonWidget <-- UIWindowHandler: tableName
deactivate UIWindowHandler
ButtonWidget -> UIWindowHandler: loadTableDesign(tableName)
activate UIWindowHandler
deactivate UIWindowHandler

@enduml