@startuml
titleLabel Add row
Actor User

User->ButtonWidget: Presses button

ButtonWidget -> TableDesignHandler: addRow()
activate TableDesignHandler
TableDesignHandler -> Table: addRow()
activate Table
loop for all Columns
    Table -> Column: addCell()
    activate Column
    create Cell
    Column -> Cell: create()
    deactivate Column
end
deactivate Table
deactivate TableDesignHandler
ButtonWidget -> UIWindowHandler: getOpenTable()
activate UIWindowHandler
ButtonWidget <-- UIWindowHandler: tableName
deactivate UIWindowHandler
ButtonWidget -> UIWindowHandler: loadTableRows(tableName)
activate UIWindowHandler
deactivate UIWindowHandler

@enduml