@startuml
title Add row
Actor User

User -> TableDesignHandler: addRow()
activate TableDesignHandler
TableDesignHandler -> Table: addRow()
activate Table
loop for all Columns
    Table -> Column: addCell()
    activate Column
    create Cell
    Column -> Cell: create()
    deactivate Column
end
deactivate Table
deactivate TableDesignHandler

@enduml