@startuml
actor User


User -> TableHandler: createTable()
activate TableHandler
create Table
TableHandler -> Table: create Table(N)
activate Table
Table -> Table: setName("TableN")
return Table
deactivate TableHandler

@enduml