@startuml
actor User

User->ButtonWidget: Presses button

ButtonWidget -> TableHandler: addTable()

activate TableHandler
create Table
TableHandler -> Table: create Table(N)
activate Table
Table -> Table: setName("TableN")
return Table
deactivate TableHandler

activate UIWindowHandler
ButtonWidget -> UIWindowHandler: loadTables()

@enduml