@startuml
actor User

User->ButtonWidget: Presses button
ButtonWidget -> AddTableCommand: execute()
AddTableCommand -> UIHandler: addTable()
UIHandler -> TableManager: addTable()
create Table
TableManager -> Table: create

AddTableCommand -> WindowCompositor: rebuildAllWindows()


@enduml