@startuml
title Delete Table\nMSS
Actor User

User->KeyEventWidget: Presses delete
activate KeyEventWidget
activate RemoveTableCommand
KeyEventWidget -> RemoveTableCommand: execute()
RemoveTableCommand ->SelectorColumn: getSelectedItem()
activate SelectorColumn
RemoveTableCommand <-- SelectorColumn: tableId
deactivate SelectorColumn
RemoveTableCommand -> UIHandler: deleteTable(tableId)
activate UIHandler
UIHandler -> TableManager: deleteTable(tableId)
TableManager -> Table: destroy()
destroy Table

deactivate UIHandler
deactivate Table

RemoveTableCommand -> WindowCompositor: rebuildAllWindows()
activate WindowCompositor
deactivate WindowCompositor
deactivate KeyEventWidget
deactivate RemoveTableCommand

@enduml