@startuml
title Delete column\nMSS
Actor User
User->KeyEventWidget: Presses delete
activate KeyEventWidget
activate RemoveColumnCommand
KeyEventWidget -> RemoveColumnCommand: execute()
RemoveColumnCommand ->SelectorColumn: getSelectedItem()
activate SelectorColumn
RemoveColumnCommand <-- SelectorColumn: columnId
deactivate SelectorColumn
RemoveColumnCommand -> UIHandler: deleteColumn(columnId)
activate UIHandler
UIHandler -> TableManager: deleteColumn(columnId)
TableManager -> Table: deleteColumn(columnId)
activate Table
alt isValidColumn(column)
    Table -> Column: destroy()
    destroy Column
else
    Table -> UIHandler: ERROR
    deactivate Table
    UIHandler -> RemoveColumnCommand: ERROR
    deactivate UIHandler
end

RemoveColumnCommand -> WindowCompositor: rebuildAllWindows()
activate WindowCompositor
deactivate WindowCompositor
deactivate RemoveColumnCommand
deactivate KeyEventWidget
@enduml