@startuml
title Delete Row\nMSS
Actor User

User->KeyEventWidget: Presses delete
activate KeyEventWidget
activate RemoveRowCommand
KeyEventWidget -> RemoveRowCommand: execute()
RemoveRowCommand ->SelectorColumn: getSelectedItem()
activate SelectorColumn
RemoveRowCommand <-- SelectorColumn: rowId
deactivate SelectorColumn
KeyEventWidget -> UIHandler: deleteRow(tableId, rowId)
activate UIHandler
UIHandler -> TableManager: deleteRow(tableId, rowId)
TableManager -> Table: deleteRow(rowId)
activate Table
loop
    Table -> Column: deleteCell(index)
    activate Column
    Column -> Cell: destroy()
    deactivate Column
    destroy Cell
end

deactivate UIHandler
deactivate Table

RemoveRowCommand -> WindowCompositor: rebuildAllWindows()
activate WindowCompositor
deactivate WindowCompositor
deactivate KeyEventWidget


@enduml