@startuml
title Delete Row\nMSS
Actor User
User->ButtonWidget: Presses delete
activate ButtonWidget
ButtonWidget ->UIWindowHandler: getSelectedItem()
activate UIWindowHandler
ButtonWidget <-- UIWindowHandler: rowIndex
deactivate UIWindowHandler

ButtonWidget -> TableRowsHandler: deleteRow(rowIndex)
activate TableRowsHandler

TableRowsHandler -> Table: isValidRowIndex(rowIndex)
activate Table
TableRowsHandler -> Table: deleteRow(rowIndex)

loop
    Table -> Column: deleteCell(index)
    activate Column
    Column -> Cell: destroy()
    deactivate Column
    destroy Cell
end
deactivate Table
deactivate TableRowsHandler
ButtonWidget -> TableRowsHandler: getOpenTable()
activate TableRowsHandler
ButtonWidget <-- TableRowsHandler: tableName
deactivate UIWindowHandler
ButtonWidget -> UIWindowHandler: removeTableRowsEntry(tableName,rowIndex)
activate UIWindowHandler
deactivate UIWindowHandler

ButtonWidget -> UIWindowHandler: loadTableRows(tableName)

activate UIWindowHandler
deactivate ButtonWidget
@enduml