@startuml
titleLabel Delete column\nMSS
Actor User
User->ButtonWidget: Presses delete
activate ButtonWidget
ButtonWidget ->UIWindowHandler: getSelectedItem()
activate UIWindowHandler
ButtonWidget <-- UIWindowHandler: columnName
deactivate UIWindowHandler
ButtonWidget -> TableDesignHandler: deleteColumn(columnName)
activate TableDesignHandler
TableDesignHandler -> Table: deleteColumn(column)
activate Table
alt isValidColumn(column)
    Table -> Column: destroy()
    destroy Column
else
    Table -> TableDesignHandler: ERROR
    deactivate Table
    TableDesignHandler -> ButtonWidget: ERROR
    deactivate TableDesignHandler
end
ButtonWidget -> UIWindowHandler: getOpenTable()
activate UIWindowHandler
ButtonWidget <-- UIWindowHandler: tableName
deactivate UIWindowHandler

ButtonWidget -> UIWindowHandler: removeTableRowsEntry(tableName,columnName)
activate UIWindowHandler
deactivate UIWindowHandler

ButtonWidget -> UIWindowHandler: loadTableDesign(tableName)
deactivate ButtonWidget
activate UIWindowHandler

@enduml