@startuml
title Delete Table\nMSS
Actor User

User -> TablesHandler: deleteTable(Table)
alt is(Valid)Table(table)
activate TablesHandler

TablesHandler -> Table: destroy()
destroy Table
else
deactivate TablesHandler
TablesHandler-> User : ERROR
end

@enduml