@startuml
title Delete column\nMSS
Actor User

User -> TableDesignHandler: deleteColumn(column)
activate TableDesignHandler
TableDesignHandler -> Table: deleteColumn(column)
activate Table
alt isValidColumn(column)
    Table -> Column: destroy()
    destroy Column
else
    Table -> TableDesignHandler: ERROR
    deactivate Table
    TableDesignHandler -> User: ERROR
    deactivate TableDesignHandler
end

@enduml