@startuml
title Edit Column Name
Actor User

User -> ModeHandler: setColumnName(column, name)
activate ModeHandler
alt mode = TableDesign
    ModeHandler -> TableDesignHandler: setColumnName(column, name)
    activate TableDesignHandler
    TableDesignHandler -> Table: setColumnName(column, name)
    activate Table
    alt !isAllReadyUsedColumnName(name)
        Table -> Column: isEmpty = isEmptyName(name)
        activate Column
        deactivate Column
        alt !isEmpty
            Table -> Column: setName(name)
            activate Column
            deactivate Column
        else
            Table -> TableDesignHandler: ERROR
            deactivate Table
            TableDesignHandler -> ModeHandler: ERROR
            ModeHandler -> User: ERROR
        end
    else
    TableDesignHandler -> ModeHandler: ERROR
    deactivate TableDesignHandler
    ModeHandler -> User: ERROR
    end
else
    ModeHandler -> User: ERROR

end


deactivate ModeHandler


@enduml