@startuml
title Edit Column Type
Actor User

loop while !isValid
    User -> ModeHandler: isValid = setColumnType(column)
    activate ModeHandler
    ModeHandler -> ModeHandler: isValidMode
    ModeHandler -> DesignHandler: isValid = setColumnType(column)
    activate DesignHandler
    DesignHandler -> Column: isValid = changeType()
    activate Column
    Column -> Column: t = getType()
    note left
        hier nog een
        return bij?
    end note
    alt t = String
        Column -> Column: setType(Email)
    else t = Email
        Column -> Column: setType(Boolean)
    else t = Boolean
        Column -> Column: setType(Integer)
    else t = Integer
        Column -> Column: setType(String)
    end
    deactivate Column
    deactivate DesignHandler
    deactivate ModeHandler
end



@enduml