@startuml
title Edit Column Blanks
Actor User


User -> TableDesignHandler: changeColumnBlanks(column)
activate TableDesignHandler
TableDesignHandler -> Table: changeColumnBlanks(column)
activate Table
Table -> Column: changeBlanks()
activate Column
alt changeOfBlanksAllowed()
    Column -> Column: b = areBlanksAllowed()
    Column -> Column: setBlanks(!b)
else
    Column -> Table: ERROR
    deactivate Column
    Table -> TableDesignHandler: ERROR
    deactivate Table
    TableDesignHandler -> User: ERROR
    deactivate TableDesignHandler
end



@enduml