@startuml
title edit tableName MSS
actor User

User -> EditorWidget: Press enter
EditorWidget -> SetTableNameCommand: execute()
SetTableNameCommand -> UIHandler: setTableName(tableId, name)
UIHandler -> TableManager: setTableName(tableId, name)
TableManager -> Table: setName(name)
SetTableNameCommand -> CommandBus: post(this)
CommandBus -> TableNameUpdater: update()
TableNameUpdater -> UIHandler: getTableName(tableId)
TableNameUpdater -> EditorWidget2: setText(tableName)


@enduml