@startuml
actor User

User -> TableHandler: setTableName(table, name)
activate TableHandler
activate Table
TableHandler -> TableHandler: isNameAlreadyUsed(name)
TableHandler -> Table: setName(name)
Table -> Table: isNameEmpty(name)
deactivate Table
deactivate TableHandler


@enduml