@startuml
title Edit Column Type
Actor User



User -> SwitchBoxWidget: changes type
activate SwitchBoxWidget
SwitchBoxWidget -> TableDesignHandler: setColumnType(column, type)
deactivate
activate TableDesignHandler
TableDesignHandler -> TableManager: setColumnType(column, type)
activate TableManager
TableManager -> Table: setColumnType(column, type)
activate Table
Table -> Column: setType(type)
activate Column

alt canHaveAsType(newType)
    create "newColumn : Column"
    Column -> "newColumn : Column": create Column
    Column --> Table: newColumn
else
    Column -> Table: ERROR
    deactivate Column
    Table -> TableManager: ERROR
    deactivate Table
    TableManager -> TableDesignHandler: ERROR
    deactivate TableManager
    TableDesignHandler -> User: ERROR
    deactivate TableDesignHandler
end





@enduml