@startuml
titleLabel Edit Column Name
Actor User


User -> EditorWidget: changes column name
activate EditorWidget
EditorWidget -> TableDesignHandler: setColumnName(column, name)
deactivate UIWindowHandler

activate TableDesignHandler
TableDesignHandler -> TableManager: setColumnName(column, name)
activate TableManager
TableManager -> Table: setColumnName(column, name)

activate Table
alt !isAllReadyUsedColumnName(name)
    Table -> Column: setName(name)
    activate Column

    opt !canHaveAsName(name)
        Column -> Table: ERROR
        deactivate Column
        Table -> TableManager: ERROR
        deactivate Table
        TableManager -> TableDesignHandler: ERROR
        deactivate TableManager
        TableDesignHandler -> User: ERROR
    end
else
TableDesignHandler -> User: ERROR
deactivate TableDesignHandler
end



@enduml