@startuml
title Edit Column Default Value
Actor User




User -> TableDesignHandler: setColumnDV(column, value)
activate TableDesignHandler
TableDesignHandler -> TableManager: setColumnDV(column, value)
activate TableManager
TableManager -> Table: setColumnDV(column, value)
activate Table
Table -> Column: setDV(value)
activate Column

opt !canHaveAsValue(value)
    Column -> Table: ERROR
    deactivate Column
    Table -> TableManager: ERROR
    deactivate Table
    TableManager -> TableDesignHandler: ERROR
    deactivate TableManager
    TableDesignHandler -> User: ERROR
    deactivate TableDesignHandler
end

@enduml