@startuml
title Delete Row\nMSS
Actor User

User -> EditorWidget: changes column name
activate EditorWidget
EditorWidget -> TableRowsHandler: setCellValue(columnName,row,value)
deactivate
activate TableRowsHandler
TableRowsHandler -> Table: isValidCell(cell, value)
activate Table
TableRowsHandler -> Table: editCell(cell, value)

Table -> Column: editCell(cell, value)
activate Column
Column -> Cell: setValue(value)
activate Cell
Cell -> Cell: isValidValue(value)
deactivate Cell
deactivate Column

deactivate Table

deactivate TableRowsHandler
@enduml