@startuml
title Edit Row Value\nMSS
Actor User

User -> EditorWidget: edits text and presses enter
activate EditorWidget
EditorWidget -> SetCellValueCommand: execute()
activate SetCellValueCommand
SetCellValueCommand -> UIHandler: setCellValue(tableId,columnId,rowId,value)
activate UIHandler
UIHandler -> TableManager: setCellValue(tableId,columnId,value)
activate TableManager
TableManager -> Table: isValidCell(value)
activate Table
TableManager -> Table: editCell(columnId,rowId,value)

Table -> Column: editCell(rowId, value)
activate Column
deactivate Column
deactivate Table

SetCellValueCommand -> CommandBus: post(this)

@enduml