@startuml
title Edit Column Name MSS
Actor User


User -> EditorWidget: Press enter
activate EditorWidget
EditorWidget -> SetColumnNameCommand: execute()
activate SetColumnNameCommand
SetColumnNameCommand -> UIHandler: setColumnName(tableId,columnId,name)
activate UIHandler
UIHandler -> TableManager: setColumnName(tableId,columnId,name)
activate TableManager
TableManager -> Table: setColumnName(columnId,name)
activate Table
Table->ColumnConverter:convertToType(column, type)
activate ColumnConverter
return newColumn
deactivate ColumnConverter
Table->Table: setColumn(columnId,newColumn)
deactivate Table
SetColumnNameCommand -> CommandBus: post(this)



@enduml