@startuml
title Edit Column Blanks MSS
Actor User

User -> CheckBoxWidget: toggles

activate CheckBoxWidget
CheckBoxWidget -> SetBlanksAllowedCommand: execute()
activate SetBlanksAllowedCommand
SetBlanksAllowedCommand -> UIHandler: setBlanksAllowed(tableId,columnId,value)
activate UIHandler
UIHandler -> TableManager: setBlanksAllowed(tableId,columnId,value)
activate TableManager
activate Table
TableManager -> Table: setBlanksAllowed(columnId,value)

Table -> Column: setBlanksAllowed(value)
activate Column
deactivate Column
deactivate Table

SetBlanksAllowedCommand -> CommandBus: post(this)



@enduml