@startuml
Actor User
User --> ButtonWidget: handleMouseEvent(...)
activate ButtonWidget

ButtonWidget -> TableHandler: isEmptyTable(selectedTableName)
activate TableHandler
ButtonWidget <-- TableHandler: True
deactivate TableHandler
ButtonWidget -> TableHandler: getTableDesignHandler(selectedTableName)
activate TableHandler
ButtonWidget <-- TableHandler: tableDesignHandler
deactivate TableHandler
ButtonWidget -> UIWindowHandler: switchToTableDesignWindow(tableDesignHandler)
deactivate ButtonWidget
activate UIWindowHandler
UIWindowHandler -> TableDesignWindow: getLayout(tableDesignHandler)
activate TableDesignWindow
TableDesignWindow -> TableDesignHandler: getColumns()
activate TableDesignHandler
...
TableDesignWindow <-- TableDesignHandler:
deactivate TableDesignHandler
UIWindowHandler <-- TableDesignWindow: layout
deactivate TableDesignWindow
UIWindowHandler -> UIWindowHandler: setLayout(layout)
deactivate UIWindowHandler

@enduml