@startuml
actor User

User -> TableHandler: isEmpty(table)
activate TableHandler
TableHandler -> Table: isEmpty()
activate Table
deactivate Table
alt empty
    TableHandler -> TableHandler: setMode(designMode)
    TableHandler -> DesignHandler: setTable(table)
    activate DesignHandler
    deactivate DesignHandler
else !empty
    TableHandler -> TableHandler: setMode(rowsMode)
    TableHandler -> RowsHandler: setTable(table)
    activate RowsHandler
    deactivate RowsHandler
end
deactivate TableHandler



@enduml