@startuml
actor User

User -> ButtonWidget: double clicks
activate ButtonWidget
ButtonWidget -> OpenTableCommand: execute()
activate OpenTableCommand
OpenTableCommand -> UIHandler: isTableEmpty(id)
activate UIHandler
deactivate UIHandler
alt empty
    OpenTableCommand -> WindowCompositor: addDesignWindow(id)
else !empty
    OpenTableCommand -> WindowCompositor: addRowsWindow(id)
end
deactivate OpenTableCommand
deactivate ButtonWidget


@enduml