@startuml
Actor User
User --> ButtonWidget: handleMouseEvent(...)
activate ButtonWidget

ButtonWidget -> UIWindowHandler: switchToTableRowsWindow(selectedTableName)
deactivate ButtonWidget
UIWindowHandler -> TableHandler: isEmptyTable(selectedTableName)
activate UIWindowHandler
activate TableHandler
UIWindowHandler <-- TableHandler: False
deactivate TableHandler
UIWindowHandler -> TableHandler: getTableRowsHandler(selectedTableName)
activate TableHandler
UIWindowHandler <-- TableHandler: tableRowsHandler
deactivate TableHandler
UIWindowHandler -> TableRowsWindow: getLayout(tableRowsHandler)
activate TableRowsWindow
TableRowsWindow -> TableRowsHandler: getRows()
activate TableRowsHandler
...
TableRowsWindow <-- TableRowsHandler:
deactivate TableRowsHandler
UIWindowHandler <-- TableRowsWindow: layout
deactivate TableRowsWindow
UIWindowHandler -> UIWindowHandler: setLayout(layout)
deactivate UIWindowHandler

@enduml