@startuml
Actor User
User --> ButtonWidget: handleMouseEvent(...)
activate ButtonWidget

ButtonWidget -> TableDesignHandler: switchToTableRowsHandler()
activate TableDesignHandler
ButtonWidget <-- TableDesignHandler: tableRowsHandler
deactivate TableDesignHandler
ButtonWidget -> UIWindowHandler: switchToTableRowsWindow(tableRowsHandler)
deactivate ButtonWidget
activate UIWindowHandler
UIWindowHandler -> TableRowsWindow: getLayout(tableRowsHandler)
activate TableRowsWindow
TableRowsWindow -> TableRowsHandler: getRows()
activate TableRowsHandler
...
TableRowsWindow <-- TableRowsHandler:
deactivate TableRowsHandler
UIWindowHandler <-- TableRowsWindow: layout
deactivate TableRowsWindow
UIWindowHandler -> UIWindowHandler: setLayout(layout)
deactivate UIWindowHandler

@enduml