@startuml
Actor User
User --> ButtonWidget: handleKeyEvent(...)
activate ButtonWidget

ButtonWidget -> UIWindowHandler: switchToTableDesignWindow(selectedTableName)
deactivate ButtonWidget
activate UIWindowHandler
UIWindowHandler -> TableHandler: getTableDesignHandler(selectedTableName)
activate TableHandler
UIWindowHandler <-- TableHandler: tableDesignHandler
deactivate TableHandler
UIWindowHandler -> TableDesignWindow: getLayout(tableDesignHandler)
activate TableDesignWindow
TableDesignWindow -> TableDesignHandler: getColumns()
activate TableDesignHandler
...
TableDesignWindow <-- TableDesignHandler:
deactivate TableDesignHandler
UIWindowHandler <-- TableDesignWindow: layout
deactivate TableDesignWindow
UIWindowHandler -> UIWindowHandler: setLayout(layout)
deactivate UIWindowHandler

@enduml