@startuml
activate CommandBus
CommandBus -> UpdateCommand: update(this)
activate UpdateCommand
UpdateCommand -> CommandBus : getIDs()
CommandBus --> UpdateCommand: IDs
alt if IDs are correct
UpdateCommand -> UIHandler: getValue()
activate UIHandler
UIHandler -> TablesHandler: getValue()
activate TablesHandler
return value : String
return value : String
UpdateCommand -> Widget: setValue(value)
end



@enduml