@startuml
titleLabel Delete row \n MSS
Actor User
Boundary System
User-> System: selectRow(row)
System --> User: indicates selected rows
User -> System: deleteSelection()
System --> User: updated rows

@enduml