@startuml
title Delete column\nMSS
Actor User
Boundary System
User -> System: selectColumn(column)
System --> User: indicateSelected
User -> System: deleteColumn()
System --> User: updated columns list


@enduml