@startuml
titleLabel Delete table \n MSS
Actor User
Boundary System
User -> System: selectTable(table)
System --> User: show selected
User -> System: deleteTable()
System --> User: updated table list



@enduml