@startuml
titleLabel Edit row value \n MSS
Actor User
Boundary System
User -> System: editCell(column,row)
note left
    Zie edit column
    default value
end note
System --> User: updated value
@enduml