@startuml
title Open table \n MSS
Actor User
Boundary System
User -> System: selectTable(table)
alt table has no columns
    System --> User:open table in Table Design
else table has colums
    System --> User:open table in Table Rows
end


@enduml